version: '3.7'
services:
  database:
    image: postgres:latest
    volumes:
      - database:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - container.env
    restart: always
  redis:
    image: redis:latest
    expose:
      - "6379"

  elasticsearch:
    image: elasticsearch:6.4.0
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_logs:/usr/share/elasticsearch/logs
    expose:
      - "9200"

  readthedocs:
    build: .
    image: readthedocs
    expose:
      - "8000"
    depends_on:
      - database
      - redis
      - elasticsearch
    volumes:
      - rtfd_static:/opt/rtfd/static
      - rtfd_builds:/opt/rtfd/user_builds
      - ./templates:/opt/rtfd/readthedocs/templates_custom,ro
    env_file:
      - container.env

  web:
    image: nginx:latest
    ports:
      - 80:80
    links:
      - readthedocs
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']

volumes:
  database:
  es_data:
  es_logs:
  rtfd_static:
  rtfd_builds:
